import React from"react";import{createRoot}from"react-dom/client";import{ClerkProvider,SignIn,SignUp,Show,UserButton,useUser}from"@clerk/react";import"./styles.css";
const API="https://bazunk-platform-core-api.onrender.com";
const providers=[["Shopify","Live","Public storefront product search and normalized catalogue data."],["Amazon","Planned","Adapter ready; approved data source required."],["eBay","Pending","Browse integration awaiting developer credentials."],["Best Buy","Pending","US catalogue integration awaiting API approval."],["WooCommerce","Next","Public Store API integration planned."],["Etsy","Planned","Marketplace catalogue integration planned."]];
function Brand(){return <a className="brand" href="/"><span className="mark">B</span><span><b>BAZUNK</b><small>DATA PLATFORM</small></span></a>}
function App(){const path=location.pathname;if(path==="/login"||path.startsWith("/login/"))return <><Nav/><main className="page"><section className="authpage"><div><span className="tag">BAZUNK ACCOUNT</span><h1>Sign in to Data Platform</h1><p>Use the same Bazunk account you use across the marketplace. Your developer API keys remain separate from your website login.</p></div><SignIn path="/login" routing="path" signUpUrl="/sign-up" fallbackRedirectUrl="/dashboard"/></section></main><Footer/></>;if(path==="/sign-up"||path.startsWith("/sign-up/"))return <><Nav/><main className="page"><section className="authpage"><div><span className="tag">CREATE ACCOUNT</span><h1>Join Bazunk Data Platform</h1><p>Create a Bazunk account to access the developer platform and, later, manage API access and usage.</p></div><SignUp path="/sign-up" routing="path" signInUrl="/login" fallbackRedirectUrl="/dashboard"/></section></main><Footer/></>;if(path==="/dashboard")return <><Nav/><Show when="signed-in" fallback={<main className="page"><section className="login"><h1>Authentication required</h1><p>Please sign in to open the Data Platform dashboard.</p><a className="primary" href="/login">Log in →</a></section></main>}><Dashboard/></Show><Footer/></>;return <><Nav/><main><section className="hero"><div><span className="tag">COMMERCE DATA INFRASTRUCTURE</span><h1>Commerce data.<br/><em>One clean API.</em></h1><p className="lead">Connect product catalogues, marketplaces and storefronts to one normalized data layer. Search, import and keep commerce data usable without provider-shaped code.</p><div className="actions"><a className="primary" href="/dashboard">Open dashboard →</a><a className="secondary" href="#providers">Explore providers</a></div><div className="trust"><span>REST API</span><span>NORMALIZED DATA</span><span>SERVER-SIDE KEYS</span><span>SYNC READY</span></div></div><DataGraphic/></section>
<section className="what" id="platform"><div><span className="tag">WHAT IT DOES</span><h2>One layer between your app and the commerce web.</h2></div><div className="featuregrid"><article><i>01</i><h3>API integrations</h3><p>Connect supported official and public commerce APIs behind a consistent Bazunk product model.</p></article><article><i>02</i><h3>Public catalogue access</h3><p>Use legitimate public storefront interfaces where platforms expose product data without private credentials.</p></article><article><i>03</i><h3>Normalization</h3><p>Turn different titles, prices, images, variants and stock formats into one predictable response.</p></article><article><i>04</i><h3>Import & sync</h3><p>Power catalogue imports now and source-aware price and availability synchronization as providers come online.</p></article></div><p className="scrapeNote"><b>About scraping:</b> Data Platform is built around APIs, permitted public catalogue interfaces and approved feeds. It does not bypass CAPTCHAs, anti-bot controls or restricted access.</p></section>
<section id="providers" className="providers"><div className="sectionHead"><span className="tag">PROVIDER NETWORK</span><h2>Build once. Reach more sources.</h2><p>Provider-specific complexity stays inside Data Platform while applications consume a stable product model.</p></div><div className="providergrid">{providers.map(([n,s,d])=><article key={n}><div><strong>{n}</strong><span className={"pill "+s.toLowerCase()}>{s}</span></div><p>{d}</p></article>)}</div></section>
<section id="developers" className="developer"><div><span className="tag">FOR DEVELOPERS</span><h2>Predictable by design.</h2><p>Versioned endpoints, scoped API keys, quotas, usage accounting and normalized product objects.</p><a href="/dashboard">Developer dashboard →</a></div><pre><code>{`GET /v1/providers
GET /v1/products/search
GET /v1/products/:provider/:id

provider=shopify
store=example.com
q=headphones`}</code></pre></section>
<section className="cta"><span className="tag">BUILT BY BAZUNK</span><h2>Product data shouldn't dictate your architecture.</h2><p>Data Platform started as Bazunk's own commerce infrastructure and is being designed as a reusable developer platform.</p><a className="primary" href="#providers">See provider status →</a></section></main><Footer/></>}
function Dashboard(){const{user}=useUser();return <main className="page"><section className="login"><span className="tag">DEVELOPER DASHBOARD</span><h1>Welcome, {user?.firstName||"developer"}.</h1><p>Your Bazunk identity is connected. Next we'll attach Platform Core clients, API keys, usage and provider access to this account.</p><div className="account"><article><small>ACCOUNT</small><b>{user?.primaryEmailAddress?.emailAddress||"Bazunk user"}</b><p>Clerk authenticated</p></article><article><small>PLATFORM</small><b>Data API</b><p>Developer access</p></article><article><small>STATUS</small><b>Connected</b><p>Identity verified</p></article></div></section></main>}function Nav(){return <header><nav><Brand/><div className="navlinks"><a href="/#platform">Platform</a><a href="/#providers">Providers</a><a href="/#developers">Developers</a><a href="/#docs">Docs</a></div><Show when="signed-out"><a className="loginbtn" href="/login">Log in <span>→</span></a></Show><Show when="signed-in"><div className="usernav"><a href="/dashboard">Dashboard</a><UserButton/></div></Show></nav></header>}
function DataGraphic(){return <div className="visual"><div className="orbit o1"></div><div className="orbit o2"></div><div className="core"><span>BAZUNK</span><b>DATA</b><small>Normalized product layer</small></div><span className="node n1">SHOPIFY</span><span className="node n2">EBAY</span><span className="node n3">API</span><span className="node n4">FEEDS</span></div>}
function Footer(){return <footer><Brand/><p>Commerce data infrastructure by Bazunk.</p><div>© {new Date().getFullYear()} Bazunk <span>·</span> Data Platform v1</div></footer>}
const clerkKey=import.meta.env.VITE_CLERK_PUBLISHABLE_KEY as string|undefined;if(!clerkKey)throw new Error("Missing VITE_CLERK_PUBLISHABLE_KEY");createRoot(document.getElementById("root")!).render(<ClerkProvider publishableKey={clerkKey} signInUrl="/login" signUpUrl="/sign-up" signInFallbackRedirectUrl="/dashboard" signUpFallbackRedirectUrl="/dashboard"><App/></ClerkProvider>);