import pg from "pg"; import { createHash } from "node:crypto"; import { config } from "./config.js"; const {Pool}=pg;
export const db=config.DATABASE_URL?new Pool({connectionString:config.DATABASE_URL,ssl:config.NODE_ENV==="production"?{rejectUnauthorized:false}:undefined,max:10}):null;
export async function migrateDatabase(){if(!db)return{configured:false,migrated:false};await db.query(`
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS api_clients(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,plan text NOT NULL DEFAULT 'developer' CHECK(plan IN('internal','developer','commercial')),monthly_quota integer NOT NULL DEFAULT 1000 CHECK(monthly_quota>=0),rate_limit_per_minute integer NOT NULL DEFAULT 60 CHECK(rate_limit_per_minute>0),active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS api_keys(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),client_id uuid NOT NULL REFERENCES api_clients(id) ON DELETE CASCADE,key_prefix text NOT NULL,key_hash text NOT NULL UNIQUE,label text NOT NULL DEFAULT 'default',scopes text[] NOT NULL DEFAULT ARRAY['products:read','providers:read','usage:read'],active boolean NOT NULL DEFAULT true,last_used_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),revoked_at timestamptz);
CREATE INDEX IF NOT EXISTS api_keys_prefix_idx ON api_keys(key_prefix);
CREATE TABLE IF NOT EXISTS usage_events(id bigserial PRIMARY KEY,client_id uuid NOT NULL REFERENCES api_clients(id) ON DELETE CASCADE,route text NOT NULL,provider text,cache_hit boolean,status_code integer,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS usage_events_client_date_idx ON usage_events(client_id,created_at DESC);`);return{configured:true,migrated:true};}
export async function bootstrapInternalClient(){if(!db||!config.apiKeys.size)return;const key=[...config.apiKeys][0];const hash=createHash("sha256").update(key).digest("hex");const existing=await db.query("SELECT client_id FROM api_keys WHERE key_hash=$1",[hash]);if(existing.rowCount){await db.query("UPDATE api_keys SET scopes=ARRAY(SELECT DISTINCT unnest(scopes || $2::text[])) WHERE key_hash=$1",[hash,["clients:manage"]]);return;}let c=await db.query("SELECT id FROM api_clients WHERE name='Bazunk Marketplace' AND plan='internal' ORDER BY created_at LIMIT 1");let id=c.rows[0]?.id;if(!id){c=await db.query("INSERT INTO api_clients(name,plan,monthly_quota,rate_limit_per_minute) VALUES('Bazunk Marketplace','internal',1000000,240) RETURNING id");id=c.rows[0].id;}await db.query("INSERT INTO api_keys(client_id,key_prefix,key_hash,label,scopes) VALUES($1,$2,$3,'Marketplace primary',$4)",[id,key.slice(0,16),hash,["products:read","providers:read","usage:read","keys:manage","clients:manage"]]);}
export async function databaseHealth(){if(!db)return{configured:false,ok:false};try{await db.query("SELECT 1");return{configured:true,ok:true};}catch{return{configured:true,ok:false};}}
